# Site settings
title: Chico UI
email: chico@mercadolibre.com
description: "A collection of easy-to-use UI components"
baseurl: "/chico"
twitter_username: chicoui
github_username:  chicoui

# Build settings
markdown: kramdown
permalink: pretty

# The folder destination where Jekyll will write files
destination: _site/

# Set the files encoding
encoding: utf-8

exclude:
  - node_modules
  - bower_components
  - Gruntfile.js
  - libs
  - package.json

include:
  - .nojekyll

gems:
  - jekyll-assets

assets:
  gzip: false
  sources:
    - assets/images
    - assets/js
    - assets/css

#ATENCION: si no anda hay que desomcentar del bash_profile #source ~/.profile