# Site settings
title: Chico UI
email: chico@mercadolibre.com
description: "A collection of easy-to-use UI components"
baseurl: ""
twitter_username: chicoui
github_username:  chicoui

# Build settings
markdown: kramdown
permalink: pretty

source: site

# The folder destination where Jekyll will write files
destination: _site/

# Set the files encoding
encoding: utf-8

exclude:
  - assets
  - css
  - js

include:
  - .nojekyll

keep_files:
  - "assets/assets"

gems:
  - jekyll-assets

assets:
  gzip: false
  sources:
    - ../bower_components/chico/dist
    - assets
    - css
    - js

#  prefix: "/assets"
